name: Build iOS frida-python extension

on:
  workflow_dispatch:  # 수동 실행

jobs:
  build-ios:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          python3 python3-pip python3-dev \
          git pkg-config \
          libglib2.0-dev libtool automake autoconf \
          libusb-1.0-0-dev

    - name: Build frida core for iOS
      run: |
        make core-iphones PYTHON=python3

    - name: Archive built _frida.so
      uses: actions/upload-artifact@v3
      with:
        name: frida-ios-python39-arm64
        path: build/tmp-ios-arm64/lib/python3.9/site-packages/frida/_frida.cpython-39-darwin.so
